# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-08 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import main.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='html_file',
            field=models.FileField(null=True, storage=main.storage.ImageStorage(), upload_to='markdown/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='html_file',
            field=models.FileField(null=True, storage=main.storage.ImageStorage(), upload_to='markdown/'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='html_file',
            field=models.FileField(null=True, storage=main.storage.ImageStorage(), upload_to='markdown/'),
        ),
    ]
